# Generated by Django 3.2.4 on 2021-06-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('price', models.DateField(default='', max_length=100)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
